//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.ComisionesxConsulta.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class panelEntities : DbContext
    {
        public panelEntities()
            : base("name=panelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_aCOMISIONESXC_UBIGEO_OFICINA> tbl_aCOMISIONESXC_UBIGEO_OFICINA { get; set; }
        public virtual DbSet<tbl_mCOMISIONESXC_CLIENTE> tbl_mCOMISIONESXC_CLIENTE { get; set; }
        public virtual DbSet<tbl_mCOMISIONESXC_TOKEN> tbl_mCOMISIONESXC_TOKEN { get; set; }
        public virtual DbSet<TBL_ACOMISIONESXC_ANIOS> TBL_ACOMISIONESXC_ANIOS { get; set; }
        public virtual DbSet<TBL_MCOMISIONESXC_CONSULTA_ANIO> TBL_MCOMISIONESXC_CONSULTA_ANIO { get; set; }
        public virtual DbSet<tbl_mCOMISIONESXC_CONSULTA> tbl_mCOMISIONESXC_CONSULTA { get; set; }
        public virtual DbSet<tbl_aCOMISIONESXC_UBIGEO_CIUDAD> tbl_aCOMISIONESXC_UBIGEO_CIUDAD { get; set; }
    }
}
