//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.ComisionesxConsulta.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aCOMISIONESXC_UBIGEO_CIUDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_aCOMISIONESXC_UBIGEO_CIUDAD()
        {
            this.tbl_aCOMISIONESXC_UBIGEO_OFICINA = new HashSet<tbl_aCOMISIONESXC_UBIGEO_OFICINA>();
            this.tbl_mCOMISIONESXC_CONSULTA = new HashSet<tbl_mCOMISIONESXC_CONSULTA>();
        }
    
        public int ID_CIUDAD { get; set; }
        public string UBIGEO_CIUDAD { get; set; }
        public string NOMBRE_CIUDAD { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_aCOMISIONESXC_UBIGEO_OFICINA> tbl_aCOMISIONESXC_UBIGEO_OFICINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mCOMISIONESXC_CONSULTA> tbl_mCOMISIONESXC_CONSULTA { get; set; }
    }
}
