//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.ComisionesxConsulta.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mCOMISIONESXC_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_mCOMISIONESXC_CLIENTE()
        {
            this.tbl_mCOMISIONESXC_CONSULTA = new HashSet<tbl_mCOMISIONESXC_CONSULTA>();
        }
    
        public int CODIGOCLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string DOCUMENTO { get; set; }
        public string CORREO { get; set; }
        public string TIPO_PRODUCTO { get; set; }
        public string NROTARJETA { get; set; }
        public string NUMEROCUENTA { get; set; }
        public Nullable<bool> TIENECONSULTA { get; set; }
        public Nullable<bool> COMPROBACION { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string ULTIMOSDIGITOSNROCUENTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mCOMISIONESXC_CONSULTA> tbl_mCOMISIONESXC_CONSULTA { get; set; }
    }
}
