//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.ComisionesxConsulta.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MCOMISIONESXC_CONSULTA_ANIO
    {
        public int ID_CONSULTADETALL { get; set; }
        public Nullable<int> CODIGOCONSULTA { get; set; }
        public Nullable<int> CODIGO_ANIO { get; set; }
    
        public virtual TBL_ACOMISIONESXC_ANIOS TBL_ACOMISIONESXC_ANIOS { get; set; }
        public virtual tbl_mCOMISIONESXC_CONSULTA tbl_mCOMISIONESXC_CONSULTA { get; set; }
    }
}
